name: Code Review

on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.5.1
        with:
          node-version: 16

      - name: Run ESLint
        run: npm run lint

  typecheck:
    name: TSC
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.5.1
        with:
          node-version: 16

      - name: Run TS Compile
        run: npm run typecheck
